services:
  rabbitmq-integrityassurance:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-integrityassurance
    ports:
      - "5673:5672"
      - "15673:15672"
  sqlserver-integrityassurance:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-integrityassurance
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      retries: 10